--USUARIO
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER eGESVEN_ADMIN IDENTIFIED BY Q1w2e3r4t5y6
TEMPORARY TABLESPACE "TEMP";

ALTER USER eGESVEN_ADMIN QUOTA UNLIMITED ON USERS;
GRANT "RESOURCE" TO eGESVEN_ADMIN;
GRANT "CONNECT" TO eGESVEN_ADMIN;
ALTER USER eGESVEN_ADMIN DEFAULT ROLE "RESOURCE","CONNECT";

CREATE TABLE ADMINISTRATIVO (
    SALARIO        INTEGER NOT NULL,
    TRABAJADOR_RUN VARCHAR2(9) NOT NULL
);

ALTER TABLE ADMINISTRATIVO ADD CONSTRAINT ADMINISTRATIVO_PK PRIMARY KEY ( TRABAJADOR_RUN );

CREATE TABLE CATEGORIA (
    COD_CATEGORIA VARCHAR2(40) NOT NULL,
    DESCRIPCION   VARCHAR2(100) NOT NULL
);

ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( COD_CATEGORIA );

CREATE TABLE CLIENTE (
    RUN            VARCHAR2(9) NOT NULL,
    USERNAME       VARCHAR2(40) NOT NULL,
    PASSWORD       VARCHAR2(100) NOT NULL,
    TIPO_CLIENTE   NUMBER NOT NULL,
    PRIMER_NOMBRE  VARCHAR2(60) NOT NULL,
    APATERNO       VARCHAR2(60) NOT NULL,
    AMATERNO       VARCHAR2(60) NOT NULL,
    IDIOMA         VARCHAR2(60) NOT NULL,
    TELEFONO       NUMBER(9) NOT NULL,
    CORREO         VARCHAR2(60) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL
);

COMMENT ON COLUMN CLIENTE.TIPO_CLIENTE IS
    'consumidor o externo';

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( RUN );

CREATE TABLE DETALLE_PRODUCTO (
    ID_DETALLE_PRODUCTO  INTEGER NOT NULL,
    PRECIO_TOTAL_SIN_IVA INTEGER NOT NULL,
    PRECIO_TOTAL_CON_IVA INTEGER NOT NULL,
    PEDIDO_RUN           VARCHAR2(9) NOT NULL,
    PEDIDO_NUMERO_PEDIDO INTEGER NOT NULL,
    PRODUCTO_ID_FICHA    INTEGER,
    CANTIDAD_PRODUCTO    INTEGER NOT NULL
);

ALTER TABLE DETALLE_PRODUCTO
    ADD CONSTRAINT DETALLE_PRODUCTO_PK PRIMARY KEY ( ID_DETALLE_PRODUCTO,
                                                     PEDIDO_RUN,
                                                     PEDIDO_NUMERO_PEDIDO );

CREATE TABLE MEDIO_DE_PAGO (
    COD_MEDIO_PAGO VARCHAR2(10) NOT NULL,
    DESCRIPCION    VARCHAR2(50) NOT NULL
);

ALTER TABLE MEDIO_DE_PAGO ADD CONSTRAINT MEDIO_DE_PAGO_PK PRIMARY KEY ( COD_MEDIO_PAGO );

CREATE TABLE PEDIDO (
    NUMERO_PEDIDO        INTEGER NOT NULL,
    FECHA_PEDIDO         DATE NOT NULL,
    PRECIO_FINAL_SIN_IVA INTEGER NOT NULL,
    PRECIO_FINAL_CON_IVA INTEGER NOT NULL,
    CLIENTE_RUN          VARCHAR2(9) NOT NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_PK PRIMARY KEY ( CLIENTE_RUN,
                                                          NUMERO_PEDIDO );

CREATE TABLE PRODUCTO (
    ID_FICHA                INTEGER NOT NULL,
    ALTO                    FLOAT NOT NULL,
    ANCHO                   FLOAT NOT NULL,
    DESCRIPCION             VARCHAR2(200) NOT NULL,
    STOCK                   INTEGER NOT NULL,
    CATEGORIA_COD_CATEGORIA VARCHAR2(40),
    NOMBRE_PRODUCTO         VARCHAR2(60) NOT NULL,
    PRECIO_UNIDAD_SIN_IVA   INTEGER NOT NULL
);

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( ID_FICHA );

CREATE TABLE RELATION_4 (
    CLIENTE_RUN                  VARCHAR2(9) NOT NULL,
    MEDIO_DE_PAGO_COD_MEDIO_PAGO VARCHAR2(10) NOT NULL
);

ALTER TABLE RELATION_4 ADD CONSTRAINT RELATION_4_PK PRIMARY KEY ( CLIENTE_RUN,
                                                                  MEDIO_DE_PAGO_COD_MEDIO_PAGO );

CREATE TABLE ROL_TRABAJADOR (
    COD_ROL           VARCHAR2(20) NOT NULL,
    DESCRIPCION_CARGO VARCHAR2(500) NOT NULL
);

ALTER TABLE ROL_TRABAJADOR ADD CONSTRAINT ROL_TRABAJADOR_PK PRIMARY KEY ( COD_ROL );

CREATE TABLE TRABAJADOR (
    RUN                    VARCHAR2(9) NOT NULL,
    USERNAME               VARCHAR2(40) NOT NULL,
    PASSWORD               VARCHAR2(100) NOT NULL,
    PRIMER_NOMBRE          VARCHAR2(60) NOT NULL,
    APATERNO               VARCHAR2(60) NOT NULL,
    AMATERNO               VARCHAR2(60) NOT NULL,
    TELEFONO               NUMBER(9) NOT NULL,
    CORREO_ELECTRONICO     VARCHAR2(40) NOT NULL,
    FECHA_REGISTRO         DATE NOT NULL,
    SALARIO                INTEGER NOT NULL,
    ROL_TRABAJADOR_COD_ROL VARCHAR2(20)
);

ALTER TABLE TRABAJADOR ADD CONSTRAINT TRABAJADOR_PK PRIMARY KEY ( RUN );

ALTER TABLE ADMINISTRATIVO
    ADD CONSTRAINT ADMINISTRATIVO_TRABAJADOR_FK FOREIGN KEY ( TRABAJADOR_RUN )
        REFERENCES TRABAJADOR ( RUN );

ALTER TABLE DETALLE_PRODUCTO
    ADD CONSTRAINT DETALLE_PRODUCTO_PEDIDO_FK FOREIGN KEY ( PEDIDO_RUN,
                                                            PEDIDO_NUMERO_PEDIDO )
        REFERENCES PEDIDO ( CLIENTE_RUN,
                            NUMERO_PEDIDO );

ALTER TABLE DETALLE_PRODUCTO
    ADD CONSTRAINT DETALLE_PRODUCTO_PRODUCTO_FK FOREIGN KEY ( PRODUCTO_ID_FICHA )
        REFERENCES PRODUCTO ( ID_FICHA );

ALTER TABLE PEDIDO
    ADD CONSTRAINT PEDIDO_CLIENTE_FK FOREIGN KEY ( CLIENTE_RUN )
        REFERENCES CLIENTE ( RUN );

ALTER TABLE PRODUCTO
    ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY ( CATEGORIA_COD_CATEGORIA )
        REFERENCES CATEGORIA ( COD_CATEGORIA );

ALTER TABLE RELATION_4
    ADD CONSTRAINT RELATION_4_CLIENTE_FK FOREIGN KEY ( CLIENTE_RUN )
        REFERENCES CLIENTE ( RUN );

ALTER TABLE RELATION_4
    ADD CONSTRAINT RELATION_4_MEDIO_DE_PAGO_FK FOREIGN KEY ( MEDIO_DE_PAGO_COD_MEDIO_PAGO )
        REFERENCES MEDIO_DE_PAGO ( COD_MEDIO_PAGO );

ALTER TABLE TRABAJADOR
    ADD CONSTRAINT TRABAJADOR_ROL_TRABAJADOR_FK FOREIGN KEY ( ROL_TRABAJADOR_COD_ROL )
        REFERENCES ROL_TRABAJADOR ( COD_ROL );